name: Go

on:
  push:
    branches: [ release-0.21-cp ]
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: make build

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "alertmanager, amtool"
        #token: ${{ secrets.GITHUB_TOKEN }}
